# Generated by Django 4.0.2 on 2022-02-02 22:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TildaCallbackModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('page_id', models.TextField()),
                ('project_id', models.TextField()),
                ('published', models.DateTimeField()),
                ('public_key', models.TextField()),
            ],
            options={
                'db_table': 'tilda_callback',
            },
        ),
        migrations.CreateModel(
            name='TildaProjectModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('external_id', models.TextField()),
                ('title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tilda_project',
            },
        ),
        migrations.CreateModel(
            name='TildaPageModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('external_id', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('css', models.JSONField()),
                ('js', models.JSONField()),
                ('images', models.JSONField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('html', models.TextField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.tildaprojectmodel')),
            ],
            options={
                'db_table': 'tilda_page',
            },
        ),
    ]
